#before_script:
#  - "export ANDROID_HOME=\"/home/ravi/Android/Sdk\""

before_script:
    - "export ANDROID_HOME=\"/android-sdk-linux\""
    - "export BUILD_HOME=$PWD"

Lint:
  script:
    - cd MiniumApps
    - chmod +x ./gradlew
    - ./gradlew lint -p launcher3/
    - echo ${CI_BUILD_REF}
    - echo ${BUILD_HOME}
    - pwd 
    - ls -lah
  artifacts:
    paths:
    - $BUILD_HOME/MiniumApps/launcher3/build/outputs/lint-results-debug.html

#Build:
#  artifacts:
#    paths:
#    - launcher3/build/outputs/apk/launcher3-debug.apk
#    - /home/gitlab-runner/builds/${CI_BUILD_REF_SLUG}/0/siempo/siem-android-app/MiniumApps/launcher3/build/outputs/apk/launcher3-debug.apk
#  script:
#    - echo ${CI_BUILD_REF}
#    - cd MiniumApps
#    - chmod +x ./gradlew
#    - ./gradlew assembleDebug

#stages:
#  - build
#  - test
#  - lint

#build:
#  stage: build
#  script:
#    - ./gradlew assembleDebug
#  artifacts:
#    paths:
#    - app/build/outputs/

#unitTests:
#  stage: test
#  script:
#    - ./gradlew test

#lintTests:
#  stage: lint
#  script:
#    - ./gradlew lint
