#before_script:
#  - "export ANDROID_HOME=\"/home/ravi/Android/Sdk\""

before_script:
    - "export ANDROID_HOME=\"/android-sdk-linux\""
    - "export BUILD_HOME=$PWD"

Lint:
  script:
    - cd MiniumApps
    - chmod +x ./gradlew
    - ./gradlew lint -p launcher3/
  artifacts:
    expire_in: "4 week"
    name: "siempo_commit_${CI_BUILD_REF}"
    paths:
     - /home/gitlab-runner/builds/5a61db0a/0/siempo/siem-android-app/MiniumApps/launcher3/build/outputs/lint-results-debug.html
    #- /home/gitlab-runner/builds/6ec47538/0/siempo/siem-android-app/MiniumApps/launcher3/build/outputs/lint-results-debug.html

Build:
  script:
    - sleep 120
    - cd MiniumApps
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    expire_in: "4 week"
    name: "siempo_commit_${CI_BUILD_REF}"
    paths:
     - /home/gitlab-runner/builds/5a61db0a/0/siempo/siem-android-app/MiniumApps/launcher3/build/outputs/apk/alpha/debug/launcher3-alpha-debug.apk
    #- /home/gitlab-runner/builds/6ec47538/0/siempo/siem-android-app/MiniumApps/launcher3/build/outputs/apk/launcher3-debug.apk
    

#stages:
#  - build
#  - test
#  - lint

#build:
#  stage: build
#  script:
#    - ./gradlew assembleDebug
#  artifacts:
#    paths:
#    - app/build/outputs/

#unitTests:
#  stage: test
#  script:
#    - ./gradlew test

#lintTests:
#  stage: lint
#  script:
#    - ./gradlew lint